// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqjhvtdhxruyrwuethxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxamh2dGRoeHJ1eXJ3dWV0aHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjkyOTcsImV4cCI6MjA2NzE0NTI5N30.Zg6dSxNasm79b-So8XhVYt5mM8eVtfh4bTgy-V1Kmu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});